name: CopsAndRobbers
version: 1.0
api-version: 1.16
main: xyz.mauwh.candr.CopsAndRobbersPlugin
permissions:
  copsandrobbers.candr:
    default: true
  copsandrobbers.cops:
    default: true
  copsandrobbers.opencells:
    default: true
  copsandrobbers.admin.item.add:
    default: op
  copsandrobbers.admin.item.debug:
    default: op